swagger: '2.0'
info:
  title: ms01
  version: 1.0.0
  description: ms01 api for new release at IBM Hursley Summit in Oct 2023 
  x-ibm-name: ms01
paths:
  /policies/{id}:
    get:
      operationId: getId
      responses:
        '200':
          description: The operation was successful.
          schema:
            $ref: '#/definitions/ms01body'
      produces:
        - application/json
      description: Retrieve id
      parameters:
        - required: true
          name: id
          in: path
          type: string
basePath: /ms01/v1
definitions:
  ms01body:
    type: object
    properties:
      policyId:
        type: string
      issueDate:
        type: string
      expirationDate:
        type: string
      policyType:
        type: string
      customerId:
        type: string
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-api-gateway
  cors:
    enabled: true
  assembly:
    execute:
      - map:
          version: 2.0.0
          title: map
          inputs:
            id:
              schema:
                type: string
              variable: request.parameters.id
          outputs:
            response:
              schema:
                $ref: '#/definitions/ms01body'
              variable: message.body
          actions:
            - set: response.policyId
              from: id
            - set: response.issueDate
              value: '''YYYY-MM-DDTHH:mm:ss.sssZ'''
            - set: response.expirationDate
              value: '''YYYY-MM-DDTHH:mm:ss.sssZ'''
            - set: response.policyType
              value: '''SampleType'''
            - set: response.customerId
              value: '''customerId'''
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
schemes:
  - https
